---
# tasks file for ubuntu_promotheus
- name: Installing Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Starting Nginx
  service:
    name: nginx
    state: started

- name: Creating /etc/prometheus Directory
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Creating /etc/prometheus Directory
  file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'

- name: Creating /var/log/prometheus Directory
  file:
    path: /var/log/prometheus
    state: directory
    mode: '0755'

- name: Creating /var/run/prometheus
  file:
    path: /var/run/prometheus
    state: directory
    mode: '0755'

- name: Downloading and Unarchiving Prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.2.1/prometheus-2.2.1.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
  register: prometheus_archive

- name: Copying Prometheus to /usr/local/bin
  shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus /usr/local/bin/"
  when: prometheus_archive.changed

- name: Copying Promtool to /usr/local/bin
  shell: "cp /tmp/prometheus-2.2.1.linux-amd64/promtool /usr/local/bin/"
  when: prometheus_archive.changed

- name: Creating Prometheus Executable
  file:
    path: /usr/local/bin/prometheus
    mode: u+x,g+x,o+x

- name: Creating Ppromtool Executable
  file:
    path: /usr/local/bin/promtool
    mode: u+x,g+x,o+x

- name: Copying prometheus.yml to /etc/prometheus
  shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus.yml /etc/prometheus/"
  when: prometheus_archive.changed

- name: Copying Consoles to /etc/promethus
  shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/consoles /etc/prometheus/"
  when: prometheus_archive.changed

- name: Copying console_libraries to /etc/promethus
  shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/console_libraries /etc/prometheus/"
  when: prometheus_archive.changed

- name: Copying Prometheus systemd.service to /etc/systemd/system/prometheus.service
  copy:
    src: "{{ src }}"
    dest: /etc/systemd/system/prometheus.service
    mode: '0755'

- name: Installing Prometheus Service
  service:
    name: prometheus
    state: started
    enabled: yes
